// https://regex101.com/r/Ly7O1x/3
module.exports = {
	passing: [
		'"0.0.4"',
		'"1.2.3"',
		'"10.20.30"',
		'"2.0.0"',
		'"1.1.7"',
		'"99999999999999999999999.999999999999999999.99999999999999999"',

		['"0.0.4"',    'simple'],
		['"1.2.3"',    'simple'],
		['"10.20.30"', 'simple'],
		['"2.0.0"',    'simple'],
		['"1.1.7"',    'simple'],

		['"0.0.4"',                                'extended'],
		['"1.2.3"',                                'extended'],
		['"10.20.30"',                             'extended'],
		['"2.0.0"',                                'extended'],
		['"1.1.7"',                                'extended'],

		['"1.1.2-prerelease+meta"',                'extended'],
		['"1.1.2+meta"',                           'extended'],
		['"1.1.2+meta-valid"',                     'extended'],
		['"1.0.0-alpha"',                          'extended'],
		['"1.0.0-beta"',                           'extended'],
		['"1.0.0-alpha.beta"',                     'extended'],
		['"1.0.0-alpha.beta.1"',                   'extended'],
		['"1.0.0-alpha.1"',                        'extended'],
		['"1.0.0-alpha0.valid"',                   'extended'],
		['"2.0.0+build.1848"',                     'extended'],
		['"1.0.0-alpha+beta"',                     'extended'],
		['"1.2.3----RC-SNAPSHOT.12.9.1--.12+788"', 'extended'],
		['"1.2.3----R-S.12.9.1--.12+meta"',        'extended'],
		['"1.2.3----RC-SNAPSHOT.12.9.1--.12"',     'extended'],
		['"1.0.0+0.build.1-rc.10000aaa-kk-0.1"',   'extended'],
	],

	failing: [
		[['""', true],                   2],
		[['""', 'semver'],               2],
		[['""', ['simple', 'extended']], 2],

		['""',                "version doesn't follow semver"],
		[['""', 'simple'],    "version doesn't follow semver"],
		[['""', 'extended'],  "version doesn't follow extended semver"],

		['"1"',               "version doesn't follow semver"],
		['"1.2"',             "version doesn't follow semver"],
		['"1.2.3-0123"',      "version doesn't follow semver"],
		['"1.2.3-0123.0123"', "version doesn't follow semver"],
		['"1.1.2+.123"',      "version doesn't follow semver"],
		['"01.1.1"',          "version doesn't follow semver"],
		['"1.01.1"',          "version doesn't follow semver"],
		['"1.1.01"',          "version doesn't follow semver"],
		['"1.2"',             "version doesn't follow semver"],

		[['"1.1.2-prerelease+meta"',                       'simple'],   "version doesn't follow semver"],
		[['"1.1.2+meta"',                                  'simple'],   "version doesn't follow semver"],
		[['"1.1.2+meta-valid"',                            'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha"',                                 'simple'],   "version doesn't follow semver"],
		[['"1.0.0-beta"',                                  'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha.beta"',                            'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha.beta.1"',                          'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha.1"',                               'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha0.valid"',                          'simple'],   "version doesn't follow semver"],
		[['"2.0.0+build.1848"',                            'simple'],   "version doesn't follow semver"],
		[['"1.0.0-alpha+beta"',                            'simple'],   "version doesn't follow semver"],
		[['"1.2.3----RC-SNAPSHOT.12.9.1--.12+788"',        'simple'],   "version doesn't follow semver"],
		[['"1.2.3----R-S.12.9.1--.12+meta"',               'simple'],   "version doesn't follow semver"],
		[['"1.2.3----RC-SNAPSHOT.12.9.1--.12"',            'simple'],   "version doesn't follow semver"],
		[['"1.0.0+0.build.1-rc.10000aaa-kk-0.1"',          'simple'],   "version doesn't follow semver"],

		[['"+invalid"',                                    'extended'], "version doesn't follow extended semver"],
		[['"-invalid"',                                    'extended'], "version doesn't follow extended semver"],
		[['"-invalid+invalid"',                            'extended'], "version doesn't follow extended semver"],
		[['"-invalid.01"',                                 'extended'], "version doesn't follow extended semver"],
		[['"alpha"',                                       'extended'], "version doesn't follow extended semver"],
		[['"alpha.beta"',                                  'extended'], "version doesn't follow extended semver"],
		[['"alpha.beta.1"',                                'extended'], "version doesn't follow extended semver"],
		[['"alpha.1"',                                     'extended'], "version doesn't follow extended semver"],
		[['"alpha+beta"',                                  'extended'], "version doesn't follow extended semver"],
		[['"alpha_beta"',                                  'extended'], "version doesn't follow extended semver"],
		[['"alpha."',                                      'extended'], "version doesn't follow extended semver"],
		[['"alpha.."',                                     'extended'], "version doesn't follow extended semver"],
		[['"beta"',                                        'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha_beta"',                            'extended'], "version doesn't follow extended semver"],
		[['"-alpha."',                                     'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha.."',                               'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha..1"',                              'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha...1"',                             'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha....1"',                            'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha.....1"',                           'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha......1"',                          'extended'], "version doesn't follow extended semver"],
		[['"1.0.0-alpha.......1"',                         'extended'], "version doesn't follow extended semver"],
		[['"01.1.1"',                                      'extended'], "version doesn't follow extended semver"],
		[['"1.01.1"',                                      'extended'], "version doesn't follow extended semver"],
		[['"1.1.01"',                                      'extended'], "version doesn't follow extended semver"],
		[['"1.2"',                                         'extended'], "version doesn't follow extended semver"],
		[['"1.2.3.DEV"',                                   'extended'], "version doesn't follow extended semver"],
		[['"1.2-SNAPSHOT"',                                'extended'], "version doesn't follow extended semver"],
		[['"1.2.31.2.3----RC-SNAPSHOT.12.09.1--..12+788"', 'extended'], "version doesn't follow extended semver"],
		[['"1.2-RC-SNAPSHOT"',                             'extended'], "version doesn't follow extended semver"],
		[['"-1.0.3-gamma+b7718"',                          'extended'], "version doesn't follow extended semver"],
		[['"+justmeta"',                                   'extended'], "version doesn't follow extended semver"],
		[['"9.8.7+meta+meta"',                             'extended'], "version doesn't follow extended semver"],
		[['"9.8.7-whatever+meta+meta"',                    'extended'], "version doesn't follow extended semver"],
		[['"999.999.999----RC-SNAPSHOT.12.09.1----..12"',  'extended'], "version doesn't follow extended semver"],
	],
};
